import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildPosixHookSpoolLines,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%KINGU_AGENT_HOOK_PORT%"=="" if defined KINGU_AGENT_HOOK_ENDPOINT if exist "%KINGU_AGENT_HOOK_ENDPOINT%" call "%KINGU_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%KINGU_AGENT_HOOK_TOKEN%"=="" if not "%KINGU_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\kingu-dev\\agent-hooks" for /r "%APPDATA%\\kingu-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%KINGU_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\kingu\\agent-hooks" for /r "%APPDATA%\\kingu\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%KINGU_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set KINGU_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%KINGU_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    ...buildPosixHookSpoolLines('command-code'),
    '__kingu_read_ancestor_var() {',
    '  __kingu_name="$1"',
    '  __kingu_pid="${PPID:-}"',
    '  while [ -n "$__kingu_pid" ] && [ "$__kingu_pid" != "0" ] && [ "$__kingu_pid" != "1" ]; do',
    '    __kingu_value=""',
    '    if [ -r "/proc/$__kingu_pid/environ" ]; then',
    '      __kingu_value=$(tr "\\000" "\\n" < "/proc/$__kingu_pid/environ" 2>/dev/null | sed -n "s/^${__kingu_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__kingu_value" ]; then',
    '      __kingu_value=$(ps eww -p "$__kingu_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__kingu_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__kingu_value" ]; then',
    '      printf "%s\\n" "$__kingu_value"',
    '      return 0',
    '    fi',
    '    __kingu_pid=$(ps -o ppid= -p "$__kingu_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__kingu_fill_from_ancestor() {',
    '  __kingu_name="$1"',
    '  case "$__kingu_name" in',
    '    KINGU_AGENT_HOOK_ENDPOINT) [ -z "${KINGU_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    KINGU_AGENT_HOOK_PORT) [ -z "${KINGU_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    KINGU_AGENT_HOOK_TOKEN) [ -z "${KINGU_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    KINGU_AGENT_HOOK_ENV) [ -z "${KINGU_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    KINGU_AGENT_HOOK_VERSION) [ -z "${KINGU_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    KINGU_PANE_KEY) [ -z "${KINGU_PANE_KEY:-}" ] || return 0 ;;',
    '    KINGU_TAB_ID) [ -z "${KINGU_TAB_ID:-}" ] || return 0 ;;',
    '    KINGU_WORKTREE_ID) [ -z "${KINGU_WORKTREE_ID:-}" ] || return 0 ;;',
    '    KINGU_AGENT_LAUNCH_TOKEN) [ -z "${KINGU_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __kingu_value=$(__kingu_read_ancestor_var "$__kingu_name") || return 0',
    '  [ -n "$__kingu_value" ] && export "$__kingu_name=$__kingu_value"',
    '}',
    '__kingu_endpoint_value() {',
    '  __kingu_endpoint_name="$1"',
    '  __kingu_endpoint_path="$2"',
    '  sed -n "s/^${__kingu_endpoint_name}=//p" "$__kingu_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__kingu_fill_from_endpoint_file() {',
    '  __kingu_endpoint_path="$1"',
    '  [ -r "$__kingu_endpoint_path" ] || return 0',
    '  __kingu_endpoint_port=$(__kingu_endpoint_value KINGU_AGENT_HOOK_PORT "$__kingu_endpoint_path")',
    '  if [ -n "${KINGU_AGENT_HOOK_PORT:-}" ] && [ -n "$__kingu_endpoint_port" ] && [ "$__kingu_endpoint_port" != "$KINGU_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __kingu_endpoint_name in KINGU_AGENT_HOOK_PORT KINGU_AGENT_HOOK_TOKEN KINGU_AGENT_HOOK_ENV KINGU_AGENT_HOOK_VERSION; do',
    '    eval "__kingu_current=\\${$__kingu_endpoint_name:-}"',
    '    [ -z "$__kingu_current" ] || continue',
    '    __kingu_endpoint_value=$(__kingu_endpoint_value "$__kingu_endpoint_name" "$__kingu_endpoint_path")',
    '    [ -n "$__kingu_endpoint_value" ] && export "$__kingu_endpoint_name=$__kingu_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Kingu pane/hook metadata, so recover it before posting.',
    'for __kingu_name in KINGU_AGENT_HOOK_ENDPOINT KINGU_AGENT_HOOK_PORT KINGU_AGENT_HOOK_TOKEN KINGU_AGENT_HOOK_ENV KINGU_AGENT_HOOK_VERSION KINGU_PANE_KEY KINGU_TAB_ID KINGU_WORKTREE_ID KINGU_AGENT_LAUNCH_TOKEN; do',
    '  __kingu_fill_from_ancestor "$__kingu_name"',
    'done',
    'if [ -n "$KINGU_AGENT_HOOK_ENDPOINT" ] && [ -r "$KINGU_AGENT_HOOK_ENDPOINT" ]; then',
    '  __kingu_fill_from_endpoint_file "$KINGU_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# KINGU_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$KINGU_AGENT_HOOK_TOKEN" ] && [ -n "$KINGU_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/kingu-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/kingu-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kingu-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kingu-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/kingu/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/kingu/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^KINGU_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$KINGU_AGENT_HOOK_PORT" ]; then',
    '      __kingu_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$KINGU_AGENT_HOOK_PORT" ] || [ -z "$KINGU_AGENT_HOOK_TOKEN" ] || [ -z "$KINGU_PANE_KEY" ]; then',
    '  spool_hook_event',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${KINGU_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Kingu-Agent-Hook-Token: ${KINGU_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${KINGU_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${KINGU_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${KINGU_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${KINGU_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${KINGU_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${KINGU_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || spool_hook_event',
    'exit 0',
    ''
  ].join('\n')
}
