/*---------------------------------------------------------------------------------------------
 *  Kingu Intelligence
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

// GENERATED by build/kingu-orca/generate-lucide-icons.mjs from the ADE's lucide-react
// (ISC license). Do not edit; run the generator again.

/** One SVG element of a lucide icon: its tag and attributes, drawn on a 24 x 24 stroke grid. */
export type KinguLucideElement = readonly [string, Readonly<Record<string, string>>];

/** The icons the ADE's footer draws, by lucide name. */
export const KINGU_LUCIDE_ICONS: Readonly<Record<string, readonly KinguLucideElement[]>> = {
	'coffee': [['path',{'d':'M10 2v2'}],['path',{'d':'M14 2v2'}],['path',{'d':'M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1'}],['path',{'d':'M6 2v2'}]],
	'memory-stick': [['path',{'d':'M12 12v-2'}],['path',{'d':'M12 18v-2'}],['path',{'d':'M16 12v-2'}],['path',{'d':'M16 18v-2'}],['path',{'d':'M2 11h1.5'}],['path',{'d':'M20 18v-2'}],['path',{'d':'M20.5 11H22'}],['path',{'d':'M4 18v-2'}],['path',{'d':'M8 12v-2'}],['path',{'d':'M8 18v-2'}],['rect',{'x':'2','y':'6','width':'20','height':'10','rx':'2'}]],
	'terminal': [['path',{'d':'M12 19h8'}],['path',{'d':'m4 17 6-6-6-6'}]],
	'plug': [['path',{'d':'M12 22v-5'}],['path',{'d':'M15 8V2'}],['path',{'d':'M17 8a1 1 0 0 1 1 1v4a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1z'}],['path',{'d':'M9 8V2'}]],
	'panels-top-left': [['rect',{'width':'18','height':'18','x':'3','y':'3','rx':'2'}],['path',{'d':'M3 9h18'}],['path',{'d':'M9 21V9'}]],
	'refresh-cw': [['path',{'d':'M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8'}],['path',{'d':'M21 3v5h-5'}],['path',{'d':'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16'}],['path',{'d':'M8 16H3v5'}]],
	'triangle-alert': [['path',{'d':'m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3'}],['path',{'d':'M12 9v4'}],['path',{'d':'M12 17h.01'}]],
	'circle-alert': [['circle',{'cx':'12','cy':'12','r':'10'}],['line',{'x1':'12','x2':'12','y1':'8','y2':'12'}],['line',{'x1':'12','x2':'12.01','y1':'16','y2':'16'}]],
	'circle-check': [['circle',{'cx':'12','cy':'12','r':'10'}],['path',{'d':'m9 12 2 2 4-4'}]],
	'download': [['path',{'d':'M12 15V3'}],['path',{'d':'M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4'}],['path',{'d':'m7 10 5 5 5-5'}]],
	'loader-circle': [['path',{'d':'M21 12a9 9 0 1 1-6.219-8.56'}]],
	'server': [['rect',{'width':'20','height':'8','x':'2','y':'2','rx':'2','ry':'2'}],['rect',{'width':'20','height':'8','x':'2','y':'14','rx':'2','ry':'2'}],['line',{'x1':'6','x2':'6.01','y1':'6','y2':'6'}],['line',{'x1':'6','x2':'6.01','y1':'18','y2':'18'}]],
	'server-off': [['path',{'d':'M7 2h13a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-5'}],['path',{'d':'M10 10 2.5 2.5C2 2 2 2.5 2 5v3a2 2 0 0 0 2 2h6z'}],['path',{'d':'M22 17v-1a2 2 0 0 0-2-2h-1'}],['path',{'d':'M4 14a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h16.5l1-.5.5.5-8-8H4z'}],['path',{'d':'M6 18h.01'}],['path',{'d':'m2 2 20 20'}]],
	'monitor-smartphone': [['path',{'d':'M18 8V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h8'}],['path',{'d':'M10 19v-3.96 3.15'}],['path',{'d':'M7 19h5'}],['rect',{'width':'6','height':'10','x':'16','y':'12','rx':'2'}]],
	'rotate-cw': [['path',{'d':'M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8'}],['path',{'d':'M21 3v5h-5'}]],
	'trash-2': [['path',{'d':'M10 11v6'}],['path',{'d':'M14 11v6'}],['path',{'d':'M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6'}],['path',{'d':'M3 6h18'}],['path',{'d':'M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2'}]],
	'x': [['path',{'d':'M18 6 6 18'}],['path',{'d':'m6 6 12 12'}]],
	'chevron-down': [['path',{'d':'m6 9 6 6 6-6'}]],
	'chevron-right': [['path',{'d':'m9 18 6-6-6-6'}]],
	'external-link': [['path',{'d':'M15 3h6v6'}],['path',{'d':'M10 14 21 3'}],['path',{'d':'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6'}]],
	'copy': [['rect',{'width':'14','height':'14','x':'8','y':'8','rx':'2','ry':'2'}],['path',{'d':'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2'}]],
	'folder-open': [['path',{'d':'m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2'}]],
	'circle': [['circle',{'cx':'12','cy':'12','r':'10'}]],
};
